### ISSUE TITLE
Why store the type of a term in a field?

### ISSUE THREAD

**Issue by MasonProtter** [shashi/SymbolicUtils.jl#17]
We currently have
https://github.com/shashi/SymbolicUtils.jl/blob/46f737893be66a67111cb5224ac4ed5e1d7d1bea/src/symbolic.jl#L31-L34
and
https://github.com/shashi/SymbolicUtils.jl/blob/46f737893be66a67111cb5224ac4ed5e1d7d1bea/src/symbolic.jl#L73-L77
Couldn't we just do 
```julia
struct Variable{T} <: Symbolic{T}
    name::Symbol
    Variable(name, ::Type{T}) where {T} = new{T}(name)
end
```
and
```julia
struct Term{T} <: Symbolic{T} 
    f::Any 
    arguments::Any 
    Term(f, ::Type{T}, arguments) where {T} = new{T}(f, arguments)
end 
```
instead?

**Comment by ChrisRackauckas** [comment]
I concur 👍 

https://github.com/SciML/ModelingToolkit.jl/blob/master/src/variables.jl#L47-L51

**Comment by shashi** [comment]
Yeah we can change that. I started out not having `T` in the type, then moved it up there and this layout just gave the constructor I wanted so I kept it :-p
